name: oldbirds
description: A new Flutter project.
version: 1.0.1+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  loveli_core:
    path: plugins/loveli_core

  get_it: ^4.0.4
  shared_preferences: ^0.5.10
  url_launcher: ^5.5.0
  flutter_svg: ^0.18.1
  shimmer: ^1.1.1
  cached_network_image: ^2.3.1
  image_picker: ^0.6.7+7
  markdown_widget: ^1.2.3
  photo_view: ^0.10.2
  carousel_slider: ^2.2.1
  sliding_up_panel: ^1.0.2
  sy_flutter_qiniu_storage: ^0.2.1
  package_info: ^0.4.1
  device_info: ^0.4.2+4
  flutter_email_sender: ^3.0.1
  path_provider: ^1.6.11
  firebase_admob: ^0.9.3+4
  animated_text_kit: ^2.2.0
  intro_views_flutter: ^2.8.1
  progress_state_button: ^1.0.1
  webview_flutter: ^0.3.22+1
  jpush_flutter: ^0.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5
  flutter_native_splash: ^0.1.9

flutter_native_splash:
  image: assets/images/ic_launch.png
  color: "EF5138"
  android_disable_fullscreen: true

flutter_icons:
  image_path: "assets/images/ic_launch.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
