name: oldbirds
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  loveli_core:
    path: plugins/loveli_core

  get_it: ^4.0.2
  shared_preferences: ^0.5.6+3
  url_launcher: ^5.4.10
  flutter_svg: ^0.17.4
  shimmer: ^1.1.1
  cached_network_image: ^2.2.0
  image_picker: ^0.6.7
  permission_handler: ^5.0.0
  markdown_widget:
    git:
      url: https://github.com/asjqkkkk/markdown_widget.git
      ref: dev
  photo_view: ^0.9.2
  carousel_slider: ^2.1.0
  sliding_up_panel: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  image_path: "assets/images/ic_launch.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
