name: oldbirds
description: A new Flutter project.
version: 1.0.1+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  loveli_core:
    path: plugins/loveli_core

  get_it: ^4.0.4
  shared_preferences: ^0.5.8
  url_launcher: ^5.5.0
  flutter_svg: ^0.17.4
  shimmer: ^1.1.1
  cached_network_image: ^2.2.0
  image_picker: ^0.6.7
  permission_handler: ^5.0.0
  markdown_widget: ^1.2.3
  photo_view: ^0.9.2
  carousel_slider: ^2.2.1
  sliding_up_panel: ^1.0.2
  sy_flutter_qiniu_storage: ^0.2.1
  package_info: ^0.4.1
  device_info: ^0.4.2+4
  flutter_email_sender: ^3.0.1
  path_provider: ^1.6.11
  firebase_admob: ^0.9.3+4
  animated_text_kit: ^2.2.0
  fancy_on_boarding: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  image_path: "assets/images/ic_launch.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
